# Generated by Django 2.2.6 on 2020-01-23 00:16

import accounts.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0009_slidergallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_header', models.TextField(blank=True, max_length=250, null=True)),
                ('post_body', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('post_images', models.ImageField(blank=True, null=True, upload_to=management.models.path_and_rename)),
                ('post_author', models.ForeignKey(default=accounts.models.CustomUser, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_sponsor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.WebCategory')),
                ('post_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.PostType')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_def_date', models.DateField(null=True)),
                ('event_plan', models.CharField(choices=[('top', 'Top event'), ('once', 'One casual event'), ('weekly', 'Once per week'), ('monthly', 'Oce per month'), ('pre', 'Pre planning')], default='pre', max_length=10)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events-upload/')),
                ('event_more', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.IntroPost')),
            ],
        ),
    ]
