# Generated by Django 2.2.6 on 2020-01-30 19:32

import accounts.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('ContactTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Email', models.EmailField(max_length=80)),
                ('Category', models.CharField(max_length=80)),
                ('Subject', models.CharField(max_length=80)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_title', models.CharField(max_length=40)),
                ('adv_address', models.TextField(null=True)),
                ('adv_images', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='IntroType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='Blog Post', max_length=40)),
                ('Type_summery', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slidergallery')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='HelvoirThuis', max_length=40)),
                ('Short_summery', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Sponsor',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_header', models.TextField(blank=True, max_length=250, null=True)),
                ('news_body', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('news_images', models.ImageField(blank=True, null=True, upload_to='post-uploads/')),
                ('news_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('news_author',
                 models.ForeignKey(default=accounts.models.CustomUser, limit_choices_to={'is_staff': True}, null=True,
                                   on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
