# Generated by Django 2.2.6 on 2019-12-24 23:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_header', models.TextField(max_length=250)),
                ('post_body', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('post_images', models.ImageField(null=True, upload_to='uploads/')),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('ContactTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Email', models.EmailField(max_length=80)),
                ('Category', models.CharField(max_length=80)),
                ('Subject', models.CharField(max_length=80)),
                ('Body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_title', models.CharField(max_length=40)),
                ('adv_address', models.TextField(null=True)),
                ('adv_images', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostType', models.CharField(default='Blog Post', max_length=40)),
                ('PostType_summery', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostCategory', models.CharField(default='Home Page', max_length=40)),
                ('Category_summery', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
