# Generated by Django 2.2.6 on 2019-12-24 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_author',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.WebCategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.PostType'),
        ),
    ]
