# Generated by Django 2.2.6 on 2020-01-01 21:34

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('homepage', '0002_auto_20191225_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_author',
            field=models.ForeignKey(default=accounts.models.CustomUser, limit_choices_to={'is_staff': True}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_images',
            field=models.ImageField(null=True, upload_to='post-uploads/'),
        ),
    ]
