# Generated by Django 2.2.6 on 2020-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('homepage', '0003_auto_20200101_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_images',
            field=models.ImageField(blank=True, null=True, upload_to='post-uploads/'),
        ),
    ]
