# Generated by Django 2.2.6 on 2020-01-03 15:55

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):
    dependencies = [
        ('homepage', '0004_auto_20200103_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_images',
            field=models.ImageField(blank=True, default=homepage.models.default_place_pics, null=True,
                                    upload_to='post-uploads/'),
        ),
    ]
