# Generated by Django 2.2.6 on 2020-01-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('homepage', '0006_auto_20200115_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_images',
            field=models.ImageField(blank=True, null=True, upload_to='post-uploads/'),
        ),
    ]
