# Generated by Django 2.2.6 on 2020-01-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20200115_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slidergallery')),
            ],
        ),
    ]
