# Generated by Django 2.2.6 on 2020-01-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_slidergallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_type',
        ),
    ]
